<a href="https://colab.research.google.com/github/biukaC/DA-Internship-ProgUA/blob/main/Final_cleaning_task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [248]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [249]:
import pandas as pd
import numpy as np

In [250]:
final=pd.read_csv('https://raw.githubusercontent.com/biukaC/DA-Internship-ProgUA/refs/heads/main/copy.csv')
cleaned=final.copy()
cleaned.head()

,ID,Lead title,Lead sale ₴,Respons. user,Created on,Modified on,Modified by,Closed at,Tags,Note 2,...,Created filled,utm_source,utm_medium,utm_campaign,utm_term,utm_content,utm_referrer,phone,email,note_full
0,63408688,[NEW] free-data-analytics — /ua/free/data-anal...,0,Vasyl F.,2026-04-06 11:37:01,2026-04-06 11:39:26,Ivan M.,NaN,NaN,NaN,...,2026-04-06 11:37:01,meta,cpc,http+|+data+analytics+++безкоштовний+курс+|+si...,статика+6,broad+interests+–+27.05,NaN,'+380732768040,gpossk469@yahoo.com,'=== First Touch ===\nutm_source: meta\nutm_me...
1,63408012,[NEW] free-data-analytics — /ua/free/data-anal...,0,Oksana B.,2026-04-06 10:40:14,2026-04-06 10:45:17,Ivan M.,NaN,NaN,NaN,...,2026-04-06 10:40:14,meta,cpc,http+|+data+analytics+++безкоштовний+курс+|+si...,статика+6,broad+interests+–+27.05,NaN,'+380994950580,rgdxg618@gmail.com,'=== First Touch ===\nutm_source: meta\nutm_me...
2,63407286,form851431729,0,Vasyl F.,2026-04-06 09:42:58,2026-04-06 10:07:01,Vasyl F.,NaN,"no1, quiz-200125",NaN,...,2026-04-06 09:42:58,NaN,NaN,NaN,NaN,NaN,https://prog.academy/ua/quiz#apply,'+380682149696,kvhfupi462@meta.ua,FE: 10\nDA: 2\nQA: 2
3,63407150,Lead #63407150,0,Vasyl F.,2026-04-06 09:29:40,2026-04-06 10:06:57,Vasyl F.,NaN,NaN,NaN,...,2026-04-06 09:29:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,63407124,[NEW] free-data-analytics — /ua/free/data-anal...,0,Natalia H.,2026-04-06 09:26:11,2026-04-06 10:10:57,Ivan M.,NaN,NaN,NaN,...,2026-04-06 09:26:11,meta,cpc,http+|+data+analytics+++безкоштовний+курс+|+si...,статика+6,broad+interests+–+27.05,NaN,'+380630563876,udbzpt476@meta.ua,'=== First Touch ===\nutm_source: meta\nutm_me...

In [251]:
print(cleaned.shape)

(658, 42)

In [252]:
cleaned.columns

Index(['ID', 'Lead title', 'Lead sale ₴', 'Respons. user', 'Created on',
       'Modified on', 'Modified by', 'Closed at', 'Tags', 'Note 2',
       'Lead stage', 'Fullname', 'Contact`s company', 'Contact respons. user',
       'Telegram', 'Оплата', 'Курс', 'Lead scoring', 'Название пакета', 'Язык',
       'REFERER', 'FORMID', 'TRANID', 'COOKIES', 'Вопрос 1', 'Вопрос 2',
       'Вопрос 3', 'Вопрос 4', 'Вопрос 5', 'gclid', 'from', 'referrer',
       'Created filled', 'utm_source', 'utm_medium', 'utm_campaign',
       'utm_term', 'utm_content', 'utm_referrer', 'phone', 'email',
       'note_full'],
      dtype='object')

In [253]:
cleaned['Lead sale ₴'].unique()

array([    0,  5000, 40000, 15000, 20000, 45000, 10000, 25000])

In [254]:
cleaned['Lead sale ₴'] = cleaned['Lead sale ₴'].astype('float64')

In [255]:
cleaned['phone'].unique()

array(["'+380732768040", "'+380994950580", "'+380682149696", nan,
       "'+380630563876", "'+380681156697", "'+380929654137",
       "'+380996452646", "'+380937181375", "'+380919463414",
       "'+380735384839", "'+380684630839", "'+380637007335",
       "'+380927789135", "'+380955972558", "'+380738252172",
       "'+380987050555", "'+380917754839", "'+380969367425",
       "'+380981159241", "'+380918134285", "'+380666239133",
       "'+380677871834", "'+380500346729", "'+380631811216",
       "'+380945182000", "'+380736313518", "'+380979140237",
       "'+380910130027", "'+380667570917", "'+380638029248",
       '+380979402003', "'+380966575986", "'+380992079575",
       "'+380956763879", "'+380981423069", "'+380505933280",
       "'+380731860396", "'+380667179614", "'+380503560227",
       "'+380991894467", "'+380500148235", "'+380972542733",
       "'+380950701864", "'+380689593034", "'+380910298468",
       "'+380968646155", "'+380928930663", "'+380506593358",
       "'+380947143369", "'+380929234928", "'+380731768150",
       "'+380935037361", "'+380921544955", "'+380969508966",
       "'+380974507095", "'+380925964147", "'+380678272255",
       "'+380969590173", "'+380739597326", "'+380732099862",
       "'+380675892073", "'+380689513373", "'+380663785473",
       "'+380678604305", "'+380966914665", "'+380991956210",
       "'+380733456322", "'+380971119361", "'+380916010661",
       "'+380682920397", "'+380954694079", "'+380632424314",
       "'+380732187917", "'+380978112558", "'+380946419663",
       "'+380960368609", "'+380503237157", "'+380965551379",
       "'+380976788012", "'+380951622383", "'+380993401872",
       "'+380632445779", "'+380961051181", '+380983851268',
       "'+380934237991", "'+380947718081", "'+380677465674",
       "'+380664794059", "'+380913346213", "'+380911235827",
       "'+380929149006", "'+380978088703", "'+380969133096",
       "'+380631668719", "'+380952754795", "'+380916081087",
       "'+380685856024", "'+380975189958", "'+380928450928",
       "'+380633143941", "'+380630585777", "'+380920151074",
       "'+380732679320", "'+380735015698", '+380683244966',
       "'+380924637313", "'+380949870011", "'+380987361040",
       "'+380688602719", "'+380941404571", "'+380914305924",
       "'+380928037850", "'+380931516525", "'+380931876437",
       "'+380925082084", "'+380739590646", "'+380663021800",
       "'+380994490722", "'+380930372774", "'+380946468357",
       "'+380926250997", '+380995947084', "'+380684218079",
       "'+380957920926", "'+380940054300", "'+380942036333",
       "'+380689320438", "'+380673013049", "'+380677401221",
       "'+380947514936", "'+380933090759", "'+380973905100",
       "'+380678692692", "'+380501943574", "'+380998350866",
       "'+380942578102", "'+380736702587", "'+380986875855",
       "'+380961442289", "'+380935682291", "'+380669250206",
       '+380921632664', "'+380686515363", "'+380953043476",
       "'+380985694003", "'+380736980930", "'+380921403544",
       "'+380998251378", "'+380631983510", "'+380678149755",
       "'+380943114982", "'+380978239095", '+380986169186',
       "'+380929012817", '+380983434346', "'+380921040109",
       "'+380501304385", "'+380991276414", "'+380952594631",
       "'+380683320769", "'+380951672417", "'+380680618205",
       "'+380737151285", "'+380660962041", "'+380976604781",
       "'+380663140499", "'+380948617915", "'+380505280994",
       "'+380639441559", "'+380980316092", "'+380989978459",
       "'+380922069830", "'+380670296493", "'+380956328141",
       "'+380955031046", "'+380951202342", "'+380735030615",
       "'+380916566571", "'+380964043345", "'+380667542182",
       '+380508291260', "'+380926589881", "'+380933976182",
       "'+380998072774", "'+380955449671", "'+380665622439",
       "'+380990138126", "'+380665064541", "'+380920660886",
       "'+380730943699", "'+380964103510", "'+380929160360",
       "'+380917332158", "'+380662709461", "'+380733741751",
       "'+380997509008", "'+380941885621", "'+380947723422",
       "'+380928509614", "'+380680383212", "'+380947236453",
       "'+380926415352", "'+380990258513", "'+380950079148",
       "'+380684535377", "'+380938145557", "'+380636620717",
       '+380962226047', "'+380934833935", "'+380689561935",
       "'+380631325326", "'+380687380799", "'+380929068828",
       "'+380949575250", "'+380968594317", "'+380508396237",
       "'+380992788615", "'+380993962765", "'+380974468394",
       "'+380918666987", "'+380974408084", "'+380662122751",
       "'+380664636685", "'+380503266993", "'+380926747365",
       "'+380969825167", "'+380685835641", "'+380503428947",
       "'+380661573918", '+380916397426', "'+380662919612",
       "'+380930809203", "'+380949339287", "'+380912215487",
       "'+380920384885", "'+380925884114", "'+380988704771",
       "'+380734588907", "'+380912315160", "'+380942204708",
       "'+380957505270", '+380919938489', "'+380985950125",
       "'+380969976545", "'+380675195310", "'+380933091177",
       "'+380676608414", "'+380989825391", "'+380509612914",
       "'+380630297235", "'+380994467703", "'+380960831527",
       "'+380677774389", "'+380687519355", "'+380952860941",
       "'+380732093183", "'+380931886930", "'+380929930726",
       "'+380949429612", "'+380949430749", "'+380501027787",
       "'+380981945356", "'+380675097106", "'+380964032045",
       "'+380924927596", "'+380663645143", "'+380500021399",
       "'+380978913657", "'+380973975393", "'+380673437796",
       "'+380500098670", "'+380685175398", "'+380981694664",
       "'+380737598136", "'+380959608402", "'+380936638939",
       "'+380984191392", "'+380507232148", "'+380664239074",
       "'+380632614981", "'+380912145858", "'+380960350627",
       "'+380675521086", "'+380957650113", "'+380502925909",
       "'+380918881683", "'+380979078691", "'+380997094311",
       "'+380506442567", "'+380974914373", "'+380955926367",
       "'+380966704389", "'+380946064778", "'+380686280568",
       "'+380671533017", "'+380994111066", "'+380679005856",
       "'+380945141656", '+380684537248', "'+380634821699",
       "'+380504862347", "'+380673055986", '+380960375026',
       "'+380665066550", "'+380921284528", "'+380992032311",
       "'+380966128310", "'+380987030626", "'+380951995540",
       "'+380934012681", "'+380738407462", "'+380929501750",
       "'+380663248140", "'+380917338670", "'+380957635500",
       "'+380737772874", "'+380676905503", "'+380969760924",
       "'+380685568740", "'+380993042573", "'+380663869506",
       "'+380993703405", "'+380985271881", "'+380925670200",
       "'+380917549350", "'+380993107686", "'+380920923576",
       "'+380678705940", "'+380958178498", '+380974058631',
       "'+380940067851", "'+380967611781", "'+380948255664",
       "'+380978914042", "'+380675454509", "'+380973413546",
       "'+380732219619", "'+380912476806", "'+380994949686",
       "'+380925641570", "'+380962669225", "'+380730180184",
       "'+380737817252", "'+380984777281", "'+380639097760",
       "'+380951186385", "'+380942824447", "'+380955459056",
       "'+380967608530", "'+380922349030", '+380689856719',
       "'+380970460003", "'+380949141521", "'+380998911385",
       '+380920531780', "'+380503010245", "'+380935184599",
       "'+380943992711", "'+380936841907", "'+380974293127",
       "'+380733045510", "'+380506180935", '+380732225468',
       "'+380683540558", "'+380974954289", "'+380984474004",
       "'+380668165182", "'+380942769417", '+380508746473',
       "'+380913650433", "'+380941749351", '+380664903790',
       "'+380500063502", '+380508538388', "'+380971061874",
       "'+380731841636", "'+380926570736", "'+380980227341",
       '+380501408183', "'+380932846295", "'+380914784444",
       "'+380955599172", '+380990084610', "'+380922211001",
       "'+380957522205", "'+380923460718", "'+380998128320",
       "'+380975582701", "'+380941186309", "'+380502265676",
       "'+380998096854", "'+380982701889", "'+380937676665",
       '+380502207806', '+380918899196', "'+380663829105",
       "'+380638085507", "'+380957691537", "'+380664124455",
       "'+380637172649", "'+380949089954", "'+380962291289",
       "'+380995410147", "'+380673766274", "'+380731023335",
       "'+380661308022", "'+380952793941", "'+380686068883",
       "'+380941249633", "'+380681289202", "'+380977010950",
       "'+380968820317", "'+380975666578", "'+380665664634",
       "'+380935817365", "'+380675375669", '+380978880400',
       "'+380735748987", "'+380931586276", "'+380997061816",
       "'+380982749438", "'+380689630358", "'+380940673647",
       "'+380958903265", "'+380995413710", "'+380635720814",
       "'+380731820069", "'+380993324424", "'+380998157023",
       "'+380969948628", "'+380668069886", '+380634117865',
       "'+380663427693", "'+380915268085", '+380935140941',
       "'+380990167963", "'+380998829619", "'+380670746909",
       "'+380634615864", "'+380941023968", "'+380631442293",
       "'+380982037240", '+380957057034', "'+380913551294",
       "'+380677548142", "'+380970519319", "'+380988196222",
       "'+380963695812", "'+380967364377", '+380665348466',
       '+380941295760', "'+380669165320", "'+380953741248",
       "'+380958604553", "'+380734734053", '+380972743627',
       "'+380929088673", "'+380974682332", "'+380678464853",
       "'+380733084819", "'+380924607808", "'+380683344195",
       '+380670199975', "'+380996048428", "'+380735402822",
       "'+380685573986", "'+380989418391", "'+380937493380",
       '+380926348534', "'+380672585156", '+380688308284',
       '+380737499533', "'+380662064983", "'+380950865503",
       "'+380679294652", '+380928940161', '+380924423967',
       '+380976325285', "'+380501956824", '+380738503097',
       "'+380671642465", "'+380502236529", "'+380639602234",
       "'+380734413590", "'+380673028959", "'+380926284759",
       '+380988355836', "'+380675167583", '+380978255856',
       "'+380630096839", "'+380949981504", "'+380637247629",
       "'+380910908255", "'+380998755528", '+380973665535',
       "'+380993703772", "'+380916957073", "'+380674195837",
       "'+380634010451", "'+380931188296", "'+380964712589",
       "'+380988320264", "'+380673198578", '+380977843097',
       "'+380953228036", "'+380968490337", "'+380956305898",
       '+380967223425', '+380732331609', "'+380979242453",
       "'+380939276392", "'+380911764986", "'+380509676134",
       '+380974257771', "'+380507722970", "'+380995408951",
       "'+380663122493", "'+380917834753", "'+380505666442",
       '+380970402734', '+380666871274', "'+380996219314",
       "'+380945652896", "'+380674121449", "'+380964469785",
       "'+380928745768", "'+380734445700", "'+380921402026",
       "'+380988145882", "'+380505661954", "'+380500885724",
       "'+380671046172", "'+380987390470", "'+380670722190",
       "'+380677829134", "'+380684190216", '+380927367548',
       "'+380981220221", '+380635162909', "'+380964646647",
       "'+380928872664", "'+380961544846", '+380956344515',
       "'+380921673879", "'+380985344357", "'+380996286672",
       "'+380925889454", "'+380926738274", "'+380921454715",
       "'+380979606059", '+380943574531', '+380918805651',
       '+380984542465', '+380933183619'], dtype=object)

In [256]:
cleaned['phone'] = (cleaned['phone']
               .fillna('')
               .astype(str)
               .str.replace(r'(?!^\+)[^\d]', '', regex=True)
               .str.strip())

print(cleaned['phone'].str.len().value_counts())

phone
12    509
0      91
13     58
Name: count, dtype: int64

In [257]:
mask = (
    cleaned['phone'].notna() &
    (cleaned['phone'] != '') &
    ~cleaned['phone'].str.startswith('+')
)

cleaned.loc[mask, 'phone'] = '+' + cleaned.loc[mask, 'phone']

In [258]:
print(cleaned['phone'].str.len().value_counts(dropna=False))

phone
13    567
0      91
Name: count, dtype: int64

In [259]:
cleaned['Respons. user'].unique()

array(['Vasyl F.', 'Oksana B.', 'Natalia H.', 'Ivan M.'], dtype=object)

In [260]:
cleaned['Respons. user'].astype(str).str.strip()

0        Vasyl F.
1       Oksana B.
2        Vasyl F.
3        Vasyl F.
4      Natalia H.
          ...
653      Vasyl F.
654    Natalia H.
655      Vasyl F.
656      Vasyl F.
657      Vasyl F.
Name: Respons. user, Length: 658, dtype: object

In [261]:
cleaned['course_name'] = (
    cleaned['Lead title']
    .combine_first(cleaned['Курс'])
    .combine_first(cleaned['Название пакета'])
    .fillna('not provided')
    .astype(str)
)

cleaned = cleaned.drop(columns  = [
    'Lead title',
    'Курс',
    'Название пакета'
    ]
)
cleaned['course_name'].head(20)

0     [NEW] free-data-analytics — /ua/free/data-anal...
1     [NEW] free-data-analytics — /ua/free/data-anal...
2                                         form851431729
3                                        Lead #63407150
4     [NEW] free-data-analytics — /ua/free/data-anal...
5     [NEW] free-data-analytics — /ua/free/data-anal...
6     [NEW] free-data-analytics — /ua/free/data-anal...
7     [NEW] free-data-analytics — /ua/free/data-anal...
8     [NEW] free-data-analytics — /ua/free/data-anal...
9     [NEW] free-data-analytics — /ua/free/data-anal...
10    [NEW] free-data-analytics — /ua/free/data-anal...
11    [NEW] free-data-analytics — /ua/free/data-anal...
12              [NEW] ai-automation — /ua/ai-automation
13    [NEW] free-data-analytics — /ua/free/data-anal...
14                                        form857398089
15    [NEW] free-data-analytics — /ua/free/data-anal...
16    [NEW] free-data-analytics — /ua/free/data-anal...
17    [NEW] free-data-analytics — /ua/free/data-anal...
18    [NEW] free-data-analytics — /ua/free/data-anal...
19    [NEW] free-data-analytics — /ua/free/data-anal...
Name: course_name, dtype: object

In [262]:
cleaned['Lead stage'].unique()

array(['Заявка', 'ЯЩ (я еще горячий, но уже остываю)', 'Недозвон',
       'Закрыто и не реализовано (наберет сам если решит)',
       'Приглашен на ивент', 'Закрыто и не реализовано (спам)',
       'Принимает решение',
       'Закрыто и не реализовано (перестал отвечать в чате)',
       'Закрыто и не реализовано (не актуально)', 'Получили квитанцию',
       'Получил материалы', 'Закрыто и не реализовано',
       'Закрыто и не реализовано (недозвон)',
       'Закрыто и не реализовано (нет нужного курса)',
       'Закрыто и не реализовано (неправильный номер)',
       'Закрыто и не реализовано (перестал брать трубку)',
       'Закрыто и не реализовано (дорого)',
       'Закрыто и не реализовано (купил у конкурентов)',
       'Записан на пробное занятие', 'Получена предоплата',
       'Закрыто и не реализовано (передумал)', 'Успешно реализовано',
       'ОЖОП (ожидается оплата)'], dtype=object)

In [263]:
cleaned['Lead stage'] = cleaned['Lead stage'].str.replace(r'\s*\(.*?\)', '', regex=True)

In [264]:
cleaned['Lead stage'].unique()

array(['Заявка', 'ЯЩ', 'Недозвон', 'Закрыто и не реализовано',
       'Приглашен на ивент', 'Принимает решение', 'Получили квитанцию',
       'Получил материалы', 'Записан на пробное занятие',
       'Получена предоплата', 'Успешно реализовано', 'ОЖОП'], dtype=object)

In [265]:
cleaned['Оплата'].unique()

array(['Нет', nan, 'Monobank частями', 'Монобанк ФОП - Новый',
       'WayForPay (USD)', 'WayForPay (EUR)', 'USDT', 'Wise (EUR)',
       'Приват банк - Юлия', 'WayForPay (PLN)'], dtype=object)

In [266]:
cleaned['Contact respons. user'].unique()

array(['Vasyl F.', 'Oksana B.', 'Natalia H.', 'Ivan M.'], dtype=object)

In [267]:
cleaned['gclid'].unique()

array([nan,
       'rECiXPy_JPjrxqg3Htze9g5qp972K76O-a9uSJKamgtWqZLOQ9KwyN4u2wWIFBJS',
       'lb__LkWTNOXKyXsJMMUR-D4sIxy8pvgbGtN-mlmlX0sj-zJ8AS_EzhW-bCVt8UHoQMxp8i5W1-05',
       '0gmH-kIVFUMoB03I42lRuboW9bYLUBR_DSz8pzXjYxaIf1lOuk_RQav_7RzjeP7eKuzDMcLXrB',
       'oZs8KqqZXNUlC03Clledp5DHFhF5uLJ6pjZWgYzY3Jl4qJM84HGKwnVTxGlOzd1W_Xmrt7P',
       '1iZDacdhYhnZVAoCr8FBcagUxgL3gvdfGAgdTv-0s-9FmzhmbBw3RCTMFnJv_ZXMkZ8714',
       'qONcs9FWT2DJ7TLxboWeaz9N-XaSLaw84BGSWeIO69_vN59wWpxKjxed9KKPzB60dITEcSpErRT9Q',
       '96KlI28GW3Ww2p1vVD2hrmPBJJhgy1rU1m8LW5GnEPwGUnsEaqoaa68wGOAbIzwY-7e23ofcPCirrbTF',
       'ddk_mMJLM9fZcat70pWFg0WJcV4W4j_wT-_UqLs-DH36Oe9vvkhEkH3CVEXMdohA',
       '55gTlmZhIoMwgnXqoundp5ZMHVXNPBQxYIirUJVMlgEXmPWfze4nNmBbShQT-Tlikk',
       'p963iA-O6Qa9qb_VeV0LWxAfSMKV1_fg4GVC7zeUEBfPPGQrDLzPYy4Tbxiz-Lb',
       'rdApnnbWvIFsSSJNPpvU1Fj2uISRJvru3nX59Y96HkWB',
       'wFprBKt6YS9IX4VY8uGKQyw_JCZtCfHWG-r0wMzunckujc3P1yzMOqoXoq',
       '_qxJHGEaqzB6TII-tT0CUiOue1n6JMgXTzgPEs5fYq',
       'gxEkdvVtlfLhRPkLMGssWnGxT5LLskuahkTgtcd5PSB-GHzNISjlZhQDQ886trOh6uYUJbgmH4nw1Ik',
       'RwRwvousWcW6TRDSGH-L4P5i-g7VDiQ7bWtWehlzSxF',
       '4QnevgeL6biyFpzLdc3l-tk3YC_pW0JQuBhA9uWKNrjYf',
       'wPsZbgh4qD3q-UMcWd1N_o1VDCj8x8YTshzdid0V-XtRM7qrjJwRpf2LqAq7tS5TwDGhCmgTsUQ',
       'gA0TXrcUyQgkyG99w8TZIMcXsOLk8HTiX5FYlNuq6oO4mYTHnAVl0wciaCkq5O9S',
       '7dGIFwSFvI8avWtcN6lpAszCG9g6sScY6PrQ6RS6jFyQ7MmKsB48Wy',
       '_55id-X9Q8k89Xhx5__jpbXDGKYhoTlXyaIUa36ZnPc9b5r0-0z',
       'zJhkQ9PprAnlsyP-Q2H8XvVVvDFu_e_xY1FKyTK6AYaYOX7TCul1VHOfKl',
       'MkOcTR8tziqDBPLvM6D7QQWzRb8CjtBzMSo70RKtHG4V5buLvOkE',
       'ZXuVkp8T460Mk9UrlXRqq4Bzcg9MVfdyGk0yVHHE-9rq5qbp7WRNf',
       'YGBNdaPobCrsc7ou5f5CDMC7ilb2JpagWemb52IeNcbtzeRO12Eefd',
       'eDqKsKEsWfJTlOtphxkh-AWPlqylMGCqUuPNHFWKhpaDZ',
       'oFp26e-LkT1VTMDuEB55SMkovFKQMI1yBEUgxnrRgar2K-vZV3HXON9BaNntD6bF2Zffsy',
       'Vt0Ek75As-VqiS1LplsBuEkkcoZ9GnDhxlq_J5L4T9tM8yU',
       '7GxMei8PBK25JW4LJHK0O_VfBowFdTy4_lwKfqp8isLTaFngMKGBDRbHQoyAjmA',
       'iA1M9T0xg70uB5YIwuBVFcxQW2I-IGneLqudWu8d6tVwmpnIjt-xrude33U2',
       'DWwVeKZJkWLk0l95eYlG3Ri23Jh0ABvcudV_iVMoMpp9WxVkqzj-JGsd',
       'sJdQgmEeuqPevF4k18oNa9WwMiS2cP-mMJDpTbfNM1t-rFRP2cW8c-Det0y3K8oyXcmRbE6z5Ug',
       'S3EfiYR0TyB-saoOrOPSAKook9V6DQx4p9cvohyZ2',
       'QK07xqIhVS2mp4cor0rjOGwIGLaNxNlQMZ8BkpIflv5hnVT_9OEJV',
       'uVzDSvtLTcflLMMMgsJ-8aQKnSg-zKEqbeBIIeFfiMerSPeLYWEQ6vMjSxiIJQ35mYjjXTMop8ICNg',
       'z5NcPtYNvPV2PGcRYzJzF3tuGVFHowYX3QqP3N1AS',
       '3LfRXaAlTwscj6PZt8JMj7vOJS359gYpcAeHcuENL7biN',
       'JWJZ7hc9EmH-frmbNM9bd2VzzcalPss05CHIHkoDI48jYniDR9ucsQRJ85F4sPGztM',
       'fvjT3NN1SRwzhH8HT2HZh0JpEg3hekqkSG_49CeRneV54qK7Rzu5udwVaq5PY7z6Dyn4hR',
       '-7goRPVYOWaFMROIKRuVdJXoagRO9OF1pro_12EBMcQGx1xpQ1E3d-Ynb6huzKCPVwKuY8',
       'sYFDwjHOBR5ijpgQOpngEm8Rlq-rHXsUgn0iokcEpW43E8WUtL1paHw49nNh8h0Vl',
       'a-gMZ9A38VrB8C_SIfUq_cud9xf5xSuE_aYdUPZMMp7boqOtcVIyEK1YrBtq',
       '2Y3OrVRX7MTXDT-f26tH6_baQy23qz4YjVJ1GJPEpzOZA',
       'HwWCKbxPUn5LQ-FQ2YEE0hcZ2D7ix8bfxsNc1NNI',
       'FXRqrg_KehmRLb1ElMwgMwNHEGnEcHmWV0Lj8Eo1B3lXNgaSRO6NhSKt5cegjDMgBww-Pb',
       'ZKiXrYpd7BC7szZufnnef4UGxCo40ESUT_Srm5CAbFolg7_2CDpMZQf4aQ8KAeZJ26kU5',
       't3Wy4QSAhUF24VkXghJ0gd9beFYv6ckFJ2ucrs55ri-qjzYbIS2',
       'm3NK_uzuZg7eom5zPo8XCZJPVcwUfgYkr3BpqQDIe-'], dtype=object)

In [268]:
cleaned['COOKIES'].unique()

array([nan,
       '_gcl_au=1.1.74306004.1780433779; _gid=GA1.2.2122448978.1780433779; _gat_gtag_UA_67536040_1=1; _ga_TX92ZQKDXS=GS2.1.s1780433779$o1$g0$t1780433779$j60$l0$h0; _fbp=fb.1.1780433779434.379506095647138633; _clck=1ujucyg%5E2%5Eg6k%5E0%5E2344; _clsk=1lnqxnd%5E1780433780128%5E1%5E1%5Ez.clarity.ms%2Fcollect; _ga=GA1.2.1606822062.1780433779; _gat=1; previousUrl=prog.academy%2Fua%2Fstart',
       'previousUrl=prog.academy%2Fua%2Fstart-da',
       '_gcl_au=1.1.798810914.1777992389; _gid=GA1.2.1264228524.1777992389; _gcl_gs=2.1.k1$i1777992388$u149178871; _gac_UA-67536040-1=1.1777992394.CjwKCAjwqubPBhBOEiwAzgZX2nyHtTZXxsize4Gwr56nWRNSYsitFRCFjaFWwQFJ5vWDyQ9PEjUGCRoCdh0QAvD_BwE; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%2262962ee8-f0d9-4c08-9b41-8af35944d357%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _tt_enable_cookie=1; _ttp=01KQW9NT3Z5Y09QADGB88RHC0K_.tt.1; quiz_ua_cookie_1=t367cookie; _gcl_aw=GCL.1777992426.CjwKCAjwqubPBhBOEiwAzgZX2nyHtTZXxsize4Gwr56nWRNSYsitFRCFjaFWwQFJ5vWDyQ9PEjUGCRoCdh0QAvD_BwE; _ga=GA1.2.249537467.1777992389; previousUrl=prog.academy%2Fua%2Fdata-analytics; _ga_TX92ZQKDXS=GS2.1.s1777992394$o1$g1$t1777992454$j60$l0$h0; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777992394883::qWhNPl7Chv1ibViVKcOP.1.1777992509358.1; ttcsid=1777992394884::2IcH-ctOE-ZqrWUWxUpk.1.1777992509358.0::1.59627.31316::114464.9.1403.13086::59597.47.12862',
       '_gid=GA1.2.500164410.1777991001; _gcl_au=1.1.1376180840.1777991001; _fbp=fb.1.1777991000678.443252874391951453; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%2290395605-c89c-41b2-8e0e-507ac337c74e%22%7D; _tt_enable_cookie=1; _ttp=01KQW8B8VT1MYK9PK0J4B9B650_.tt.1; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _ga=GA1.2.1786050990.1777991001; previousUrl=prog.academy%2Fua%2Fdata-analytics; _ga_TX92ZQKDXS=GS2.1.s1777991000$o1$g1$t1777991099$j60$l0$h0; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777991000956::_8PzMQ-oa_hzsQdq9TjG.1.1777991358346.1; ttcsid=1777991000956::_eUC8zPy52qJ7ZbJ2KYP.1.1777991358346.0::1.318162.0::357375.20.1780.14870::320564.290.14555',
       '_tt_enable_cookie=1; _ttp=01K3DT7FAJHM10GD35FR6C82HD_.tt.1; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%22b586c802-5c98-47f6-831d-b8398c268350%22%7D; _fbp=fb.1.1756031598538.741742651780285134; _clck=ibad39%5E2%5Eg1a%5E0%5E2062; _gcl_au=1.1.1584506635.1771836232; _gid=GA1.2.58491147.1777812241; _gat_gtag_UA_67536040_1=1; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _gat=1; previousUrl=prog.academy%2Fua%2Fdata-analytics; _ga=GA1.2.1765395229.1756031598; _ga_TX92ZQKDXS=GS2.1.s1777904279$o415$g1$t1777904299$j40$l0$h0; _fbc=fb.1.1774443596133.IwY2xjawQwut1leHRuA2FlbQIxMQBzcnRjBmFwcF9pZAwzNTA2ODU1MzE3MjgAAR69urZesmiuaWOA1guI_tW-zoVx6H4BEvMqb1NwX7Fzt1UDRGFfPbSu3VHiAg_aem_WDgm1xHKCf1UgC5f_MXJRg%25252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252523apply; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777904279463::SB5JVTC-pRVP0cXXtlne.260.1777904305877.1; ttcsid=1777904279464::ZFznMnH0C6zpokozjyLD.431.1777904305877.0::1.20236.17907::26383.6.1130.12867::20201.1.12635',
       'ttcsid=1777784450378::lIMKvGqD8mkvVWUzg6zV.1.1777784619208.0::1.17893.0::168807.10.361.14219::157316.252.13920; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777784450377::ueHcsLHAC66eCw5ktKqB.1.1777784619208.1; _ga_TX92ZQKDXS=GS2.1.s1777784450$o1$g0$t1777784475$j35$l0$h0; _fbp=fb.1.1777784450394.149400702389453481; previousUrl=prog.academy%2Fdevops; _ga=GA1.2.256436890.1777784449; _gac_UA-67536040-1=1.1777784452.CjwKCAjwzLHPBhBTEiwABaLsSvFFolj3G6UccxO2jrWs_YagU6NHYGexd6AlTBk0jHRYnrSIGKNpsxoCUMkQAvD_BwE; _gid=GA1.2.1055558499.1777784449; _tt_enable_cookie=1; _ttp=01KQP3BVA8MHAJ34EZS7PP5WXW_.tt.1; rngst=%7B%22clientId%22%3A%228a8291a0-1429-4e98-b24a-b098f3a94133%22%7D; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _gcl_au=1.1.1227713550.1777784449; _gcl_aw=GCL.1777784450.CjwKCAjwzLHPBhBTEiwABaLsSvFFolj3G6UccxO2jrWs_YagU6NHYGexd6AlTBk0jHRYnrSIGKNpsxoCUMkQAvD_BwE; _gcl_gs=2.1.k1$i1777784447$u208446803',
       '_gcl_au=1.1.832200889.1777745183; _gid=GA1.2.1232280774.1777745183; _fbp=fb.1.1777745183749.135126524288298668; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%22a44fc826-009a-48ad-802c-7437b84d6f19%22%7D; _tt_enable_cookie=1; _ttp=01KQMXXH28J8S3BKAMZBDS9EWZ_.tt.1; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; previousUrl=prog.academy%2Fqa; _ga_TX92ZQKDXS=GS2.1.s1777745183$o1$g1$t1777745216$j27$l0$h0; _ga=GA1.2.1048323412.1777745183; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777745183819::VZRpTPGIP8SIHcjd5e3s.1.1777745277484.1; ttcsid=1777745183820::wh820Nc9JMJCGHwIVXqw.1.1777745277484.0::1.71255.33136::93625.6.172.16533::71247.82.15959',
       '_gcl_au=1.1.193042359.1777387671; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%2253daf9a6-4a0b-4c9a-b332-26050de97c0c%22%7D; _tt_enable_cookie=1; _ttp=01KQA8Z4JBMWFJM0G17J79RD27_.tt.1; _fbp=fb.1.1777387672234.547458657750624705; _gcl_gs=2.1.k1$i1777388802$u174352739; _gac_UA-67536040-1=1.1777388806.CjwKCAjwtcHPBhADEiwAWo3sJjJM4zwBbRLCbfFhazFFMgzCcVtCWRWXgUvd0oIcnJJO8BnqJRPPFRoCd78QAvD_BwE; _gcl_aw=GCL.1777388806.CjwKCAjwtcHPBhADEiwAWo3sJjJM4zwBbRLCbfFhazFFMgzCcVtCWRWXgUvd0oIcnJJO8BnqJRPPFRoCd78QAvD_BwE; _gid=GA1.2.1364598981.1777648820; _ga_TX92ZQKDXS=GS2.1.s1777656904$o5$g0$t1777656904$j60$l0$h0; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _ga=GA1.2.1239458864.1777387671; previousUrl=prog.academy%2Fua%2Fqa; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777656904745::OHF-VBni30hn7M96e3d4.5.1777657033962.1; ttcsid=1777656904746::TX4PaZEUFI9wj9-RaYGz.5.1777657033962.0::1.-2245.0::129110.11.269.12971::47326.82.12497',
       '_tt_enable_cookie=1; _ttp=01K3DT7FAJHM10GD35FR6C82HD_.tt.1; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%22b586c802-5c98-47f6-831d-b8398c268350%22%7D; _fbp=fb.1.1756031598538.741742651780285134; _clck=ibad39%5E2%5Eg1a%5E0%5E2062; _gcl_au=1.1.1584506635.1771836232; _gid=GA1.2.889740543.1777201616; _gat_gtag_UA_67536040_1=1; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _gat=1; _ga_TX92ZQKDXS=GS2.1.s1777628035$o405$g1$t1777628050$j45$l0$h0; _ga=GA1.2.1765395229.1756031598; previousUrl=prog.academy%2Fua%2Ftwo-courses; _fbc=fb.1.1774443596133.IwY2xjawQwut1leHRuA2FlbQIxMQBzcnRjBmFwcF9pZAwzNTA2ODU1MzE3MjgAAR69urZesmiuaWOA1guI_tW-zoVx6H4BEvMqb1NwX7Fzt1UDRGFfPbSu3VHiAg_aem_WDgm1xHKCf1UgC5f_MXJRg%252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252525252523apply; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777628035097::KNp7I5iUPzNKDTj5NDcq.246.1777628067188.1; ttcsid=1777628035098::bBjmTLsMU8LFnSupRk_s.417.1777628067188.0::1.14403.15352::32032.3.1126.2502::28433.51.2177',
       '_fbc=fb.1.1777526634943.PAZXh0bgNhZW0CMTEAc3J0YwZhcHBfaWQPMTI0MDI0NTc0Mjg3NDE0AAGnz_pHPOHb65PC9RVYcfKMigHo9xBKeDo_V91jIhvXCDUlOvrWTCYHflkrOMU_aem_Z5ltD6WfnSziOFjHGqXQgA; _fbp=fb.1.1777526634936.476912801827034897; ttcsid=1777526635236::ifAqxu2pUsUZEYtYUi8r.1.1777526741164.0::1.-2059.0::105881.6.302.6463::86825.109.6151; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777526635236::F_4v-VlKV_vh5UTZ8456.1.1777526741163.1; previousUrl=prog.academy%2Fua%2Fdata-analytics-free; _ga=GA1.2.1663664204.1777526635; _gid=GA1.2.91123077.1777526635; _tt_enable_cookie=1; _ttp=01KQEDFYQ25CK90YZ1E409TA37_.tt.1; rngst=%7B%22clientId%22%3A%22794f287e-05bd-491e-8863-9a717300677f%22%7D; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _ga_TX92ZQKDXS=GS2.1.s1777526634$o1$g0$t1777526634$j60$l0$h0; _gcl_au=1.1.2093126118.1777526635',
       '_gcl_aw=GCL.1777372276.EAIaIQobChMI84fZu6uQlAMVRIKDBx1QLg26EAAYASAAEgKeYPD_BwE; _gcl_gs=2.1.k1$i1777372273$u174352739; _gcl_au=1.1.572718868.1777372276; _gid=GA1.2.1335287360.1777372276; _ga_TX92ZQKDXS=GS2.1.s1777372276$o1$g0$t1777372276$j60$l0$h0; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%22a1e93110-87ee-4c2d-82ab-239a503e6808%22%7D; _fbp=fb.1.1777372276452.90099509386850981; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _tt_enable_cookie=1; _ttp=01KQ9T9A2E5XJNXDR21XHB00S2_.tt.1; _ga=GA1.2.1389109514.1777372276; _gac_UA-67536040-1=1.1777372278.EAIaIQobChMI84fZu6uQlAMVRIKDBx1QLg26EAAYASAAEgKeYPD_BwE; previousUrl=prog.academy%2Fua%2Fqa; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777372276817::SdQAXJdu9KuBGBOrSn_L.1.1777372527955.1; ttcsid=1777372276818::rpWckJcqhYMx2QivE82m.1.1777372527955.0::1.55858.0::251096.7.1175.10724::135286.3.10513',
       '_fbp=fb.1.1777356214083.148689546145693594; ttcsid=1777356214062::p1j1Qd4nwQTrJgKfNWjY.1.1777356286979.0::1.40063.0::72890.7.286.16169::71535.107.15660; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777356214062::gxP22pyVt_JF1ImnL9CD.1.1777356286979.1; previousUrl=prog.academy%2Fua%2Fqa; _ga=GA1.2.424690094.1777356213; _gac_UA-67536040-1=1.1777356215.Cj0KCQjwkrzPBhCqARIsAJN460klroRrsKUtd0yAKsLiWg9aaAyy2AJxrtpnK-6wEn4gcuq8WF5uKs4aAs3hEALw_wcB; _gid=GA1.2.684181559.1777356213; _tt_enable_cookie=1; _ttp=01KQ9AZ3SA5PDAHPE81M088H54_.tt.1; _ga_TX92ZQKDXS=GS2.1.s1777356213$o1$g0$t1777356213$j60$l0$h0; _gcl_au=1.1.32589662.1777356213; _gcl_aw=GCL.1777356213.Cj0KCQjwkrzPBhCqARIsAJN460klroRrsKUtd0yAKsLiWg9aaAyy2AJxrtpnK-6wEn4gcuq8WF5uKs4aAs3hEALw_wcB; _gcl_gs=2.1.k1$i1777356211$u174352739; rngst=%7B%22clientId%22%3A%223524f876-8945-4883-82b6-aab6b62063f4%22%7D; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D',
       '_gcl_au=1.1.1742574758.1777335054; _gid=GA1.2.2050403507.1777335054; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%22601205ee-85a5-4ea9-bb71-00330567b9a5%22%7D; _tt_enable_cookie=1; _ttp=01KQ8PSC2A5BHQZ831RAVMS4B4_.tt.1; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _fbp=fb.1.1777335054502.72362028839287833; _ga=GA1.2.1528867746.1777335054; previousUrl=prog.academy%2Fua%2Ffree-course; _ga_TX92ZQKDXS=GS2.1.s1777335054$o1$g0$t1777335083$j31$l0$h0; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777335054415::oAtJbMgcTDBsTjCJMtqt.1.1777335174393.1; ttcsid=1777335054417::FJ6o2R0MR-w3jc_8LG72.1.1777335174394.0::1.29263.0::119937.8.313.8726::105837.264.8259',
       '_fbp=fb.1.1777298660776.171068706651053505; ttcsid=1777298610591::qjM1zdQGe1Nur_wt7W7k.1.1777299049089.0::1.50235.0::438474.13.310.12686::438096.270.12557; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777298610590::nuwUlKLuS74t18bDB_wk.1.1777299049089.1; _ga_TX92ZQKDXS=GS2.1.s1777298610$o1$g1$t1777298958$j60$l0$h0',
       '_gcl_gs=2.1.k1$i1777292607$u111111236; _gcl_au=1.1.1982343069.1777292617; _gid=GA1.2.581101407.1777292618; _gac_UA-67536040-1=1.1777292618.Cj0KCQjwkrzPBhCqARIsAJN460kpXp9ZG6-IBLi7OOfCXycy4sisaOtP2AUabnQ9anIX5onHi7AQxakaAs8-EALw_wcB; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%2268d1b602-acd9-4f94-8381-2c998089adad%22%7D; _tt_enable_cookie=1; _ttp=01KQ7EAF0YBFWK4M9D82A4E5KF_.tt.1; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _gcl_aw=GCL.1777292639.Cj0KCQjwkrzPBhCqARIsAJN460kpXp9ZG6-IBLi7OOfCXycy4sisaOtP2AUabnQ9anIX5onHi7AQxakaAs8-EALw_wcB; _ga_TX92ZQKDXS=GS2.1.s1777292622$o1$g1$t1777292638$j44$l0$h0; _ga=GA1.2.901462394.1777292618; previousUrl=prog.academy%2Fua%2Fcontacts; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777292622901::nWkSll4KaniUb3BuJspL.1.1777292712877.1; ttcsid=1777292622912::lZeYwiauy2mrdonC2Hux.1.1777292712877.0::1.68420.15403::89903.4.1031.1077::68286.9.914',
       '_gcl_gs=2.1.k2$i1777240921$u120548425; _gcl_au=1.1.1590679305.1777240929; _gid=GA1.2.1325296714.1777240930; _gac_UA-67536040-1=1.1777240930.Cj0KCQjw77bPBhC_ARIsAGAjjV9kDCeDDg2WL94ZzZHpRb_hg0E2raXAh1YFxz7uxdRpR48IwRdv5BUaAqRQEALw_wcB; _gcl_aw=GCL.1777240931.Cj0KCQjw77bPBhC_ARIsAGAjjV9kDCeDDg2WL94ZzZHpRb_hg0E2raXAh1YFxz7uxdRpR48IwRdv5BUaAqRQEALw_wcB; _ga=GA1.1.615528300.1777240930; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst=%7B%22clientId%22%3A%224c6e6f4f-bd64-450a-a7a6-7c40423d94a2%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _tt_enable_cookie=1; _ttp=01KQ5X10H9G5DTKRCGNHG92BBY_.tt.1; _fbp=fb.1.1777240933269.466612127965912054; previousUrl=prog.academy%2Fpython; _ga_TX92ZQKDXS=GS2.1.s1777240930$o1$g1$t1777241064$j60$l0$h0; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777240932957::ovllGY23kJCS-jSP9fEC.1.1777241166113.1; ttcsid=1777240932967::0XHvLUL54ibCkAfDXdTY.1.1777241166115.0::1.122614.0::233030.7.106.19241::232803.269.18838',
       'ttcsid=1777066138542::UNqJny1p4HWOkkRaQYjJ.1.1777066344985.0::1.-4720.0::206409.2.998.7628::97642.198.7294; ttcsid_D4OLJ6RC77UCJ0N6Q4EG=1777066138541::jYGk_tkZU-GTCCp8JuRB.1.1777066344985.1; _fbp=fb.1.1777066138341.795600717247617006; _tt_enable_cookie=1; _ttp=01KQ0PAPX0MQ6CEZHK3NZYD0NX_.tt.1; previousUrl=prog.academy%2Fqa; rngst=%7B%22clientId%22%3A%22cb0993a7-b5ae-4771-90af-acfe0b753458%22%7D; rngstHash=%7B%22hash%22%3A%225e2cb14a18f2ee12124ef59f87d5a7f8573aa482%22%7D; rngst_callback=%7B%22callbackNumber%22%3Afalse%2C%22inactive_project%22%3Afalse%2C%22ip_is_blocked%22%3Afalse%2C%22recaptcha%22%3A0%7D; _ga=GA1.2.296947503.1777066137; _ga_TX92ZQKDXS=GS2.1.s1777066137$o1$g0$t1777066137$j60$l0$h0; _gac_UA-67536040-1=1.1777066138.CjwKCAjwqazPBhALEiwAOuXqdIEl3ID5KG-I1eAh34kEeomE4kFb01zWgzifqW49zM5Pc5cF6002ShoCjQoQAvD_BwE; _gcl_aw=GCL.1777066137.CjwKCAjwqazPBhALEiwAOuXqdIEl3ID5KG-I1eAh34kEeomE4kFb01zWgzifqW49zM5Pc5cF6002ShoCjQoQAvD_BwE; _gcl_gs=2.1.k1$i1777066133$u154568185; _gid=GA1.2.301780198.1777066137; _gcl_au=1.1.1411787112.1777066136',

In [269]:
cleaned['Contact`s company'].unique()

array([nan, 'Company name not specified', 'Название не указано'],
      dtype=object)

In [270]:
cleaned['FORMID'].unique()

array([nan, 'form903852865', 'form1589907761', 'form832761338',
       'form585353266', 'form386680255', 'form386680324',
       'form2224655633', 'form1725743711', 'form386680340',
       'form402927681', 'form746407167', 'form386681322', 'form386680242',
       'form832761319', 'form386681409', 'form835935717', 'form417774864',
       'form417774833', 'form386686393', 'form585353325'], dtype=object)

In [271]:
cleaned['Modified by'].unique()

array(['Ivan M.', 'Vasyl F.', 'Oksana B.', 'Natalia H.', nan],
      dtype=object)

In [272]:
cleaned = cleaned.drop(columns =['gclid','COOKIES','Contact`s company'])

In [273]:
cleaned['manager'] = cleaned[
    ['Respons. user', 'Contact respons. user','Modified by']
].bfill(axis=1).iloc[:, 0]

cleaned = cleaned.drop(columns=[
    'Respons. user',
    'Contact respons. user',
    'Modified by'
])

In [274]:
cleaned['manager'].value_counts()

manager
Oksana B.     228
Natalia H.    218
Vasyl F.      211
Ivan M.         1
Name: count, dtype: int64

In [275]:
cleaned['manager'].isna().sum()

np.int64(0)

In [276]:
cleaned['utm_referrer'] = (
    cleaned['utm_referrer']
    .combine_first(cleaned['REFERER'])
    .combine_first(cleaned['referrer'])
)

cleaned = cleaned.drop(columns= [
    'REFERER',
    'referrer'
])

In [277]:
cleaned.columns

Index(['ID', 'Lead sale ₴', 'Created on', 'Modified on', 'Closed at', 'Tags',
       'Note 2', 'Lead stage', 'Fullname', 'Telegram', 'Оплата',
       'Lead scoring', 'Язык', 'FORMID', 'TRANID', 'Вопрос 1', 'Вопрос 2',
       'Вопрос 3', 'Вопрос 4', 'Вопрос 5', 'from', 'Created filled',
       'utm_source', 'utm_medium', 'utm_campaign', 'utm_term', 'utm_content',
       'utm_referrer', 'phone', 'email', 'note_full', 'course_name',
       'manager'],
      dtype='object')

In [278]:
print(cleaned.shape)

(658, 33)

In [279]:
cleaned.to_csv('/content/drive/MyDrive/DA Internship ProgAcademy/Final version/cleaned.csv', index=False, encoding='utf-8-sig')

In [280]:
print("Saved locally (Google Drive). For GitHub usage, upload copy.csv or use raw link:")
print("https://raw.githubusercontent.com/biukaC/DA-Internship-ProgUA/refs/heads/main/cleaned.csv")

Saved locally (Google Drive). For GitHub usage, upload copy.csv or use raw link:
https://raw.githubusercontent.com/biukaC/DA-Internship-ProgUA/refs/heads/main/cleaned.csv